const playerDatabase = [
  { name: "Cristiano Ronaldo", rating: 98 },
  { name: "Lionel Messi", rating: 97 },
  { name: "Kylian Mbappé", rating: 95 },
  { name: "Erling Haaland", rating: 95 },
  { name: "Kevin De Bruyne", rating: 94 },
  { name: "Rodri", rating: 93 },
  { name: "Harry Kane", rating: 93 },
  { name: "Vinícius Jr.", rating: 92 },
  { name: "Mohamed Salah", rating: 91 },
  { name: "Robert Lewandowski", rating: 91 },
  { name: "Thibaut Courtois", rating: 91 },
  { name: "Alisson Becker", rating: 90 },
  { name: "Marc-André ter Stegen", rating: 90 },
  { name: "Virgil van Dijk", rating: 90 },
  { name: "Rúben Dias", rating: 89 },
  { name: "Bernardo Silva", rating: 89 },
  { name: "Jude Bellingham", rating: 89 },
  { name: "Luka Modrić", rating: 88 },
  { name: "Toni Kroos", rating: 88 },
  { name: "Bruno Fernandes", rating: 88 },
  { name: "Antoine Griezmann", rating: 88 },
  { name: "Son Heung-min", rating: 87 },
  { name: "Neymar Jr", rating: 87 },
  { name: "Karim Benzema", rating: 87 },
  { name: "Joshua Kimmich", rating: 87 },
  { name: "Jan Oblak", rating: 87 },
  { name: "Ederson", rating: 87 },
  { name: "Bukayo Saka", rating: 86 },
  { name: "Martin Ødegaard", rating: 86 },
  { name: "Frenkie de Jong", rating: 86 },
  { name: "Pedri", rating: 86 },
  { name: "Rafael Leão", rating: 86 },
  { name: "Victor Osimhen", rating: 86 },
  { name: "Lautaro Martínez", rating: 86 },
  { name: "Paulo Dybala", rating: 85 },
  { name: "Ilkay Gündoğan", rating: 85 },
  { name: "Declan Rice", rating: 85 },
  { name: "William Saliba", rating: 85 },
  { name: "Achraf Hakimi", rating: 85 },
  { name: "Trent Alexander-Arnold", rating: 85 },
  { name: "Alphonso Davies", rating: 84 },
  { name: "Theo Hernández", rating: 84 },
  { name: "João Cancelo", rating: 84 },
  { name: "Marquinhos", rating: 84 },
  { name: "Eder Militão", rating: 84 },
  { name: "Ronald Araújo", rating: 84 },
  { name: "Mike Maignan", rating: 84 },
  { name: "Emiliano Martínez", rating: 84 },
  { name: "Bruno Guimarães", rating: 84 },
  { name: "Jamal Musiala", rating: 84 },
  { name: "Phil Foden", rating: 84 },
  { name: "Florian Wirtz", rating: 84 },
  { name: "Khvicha Kvaratskhelia", rating: 84 },
  { name: "Marcus Rashford", rating: 83 },
  { name: "Jack Grealish", rating: 83 },
  { name: "Ousmane Dembélé", rating: 83 },
  { name: "Kingsley Coman", rating: 83 },
  { name: "Leroy Sané", rating: 83 },
  { name: "Serge Gnabry", rating: 83 },
  { name: "Federico Valverde", rating: 83 },
  { name: "Eduardo Camavinga", rating: 83 },
  { name: "Aurélien Tchouaméni", rating: 83 },
  { name: "Gavi", rating: 83 },
  { name: "Enzo Fernández", rating: 82 },
  { name: "Alexis Mac Allister", rating: 82 },
  { name: "Julian Álvarez", rating: 82 },
  { name: "Darwin Núñez", rating: 82 },
  { name: "Luis Díaz", rating: 82 },
  { name: "Cody Gakpo", rating: 82 },
  { name: "Diogo Jota", rating: 82 },
  { name: "Alexander Isak", rating: 82 },
  { name: "Gabriel Jesus", rating: 82 },
  { name: "Gabriel Martinelli", rating: 82 },
  { name: "Kai Havertz", rating: 82 },
  { name: "Raheem Sterling", rating: 81 },
  { name: "Riyad Mahrez", rating: 81 },
  { name: "Sadio Mané", rating: 81 },
  { name: "N'Golo Kanté", rating: 81 },
  { name: "Paul Pogba", rating: 81 },
  { name: "Marco Reus", rating: 81 },
  { name: "Thomas Müller", rating: 81 },
  { name: "Angel Di Maria", rating: 81 },
  { name: "Olivier Giroud", rating: 81 },
  { name: "Ciro Immobile", rating: 81 },
  { name: "Romelu Lukaku", rating: 81 },
  { name: "Dusan Vlahović", rating: 81 },
  { name: "Federico Chiesa", rating: 81 },
  { name: "Nicolo Barella", rating: 81 },
  { name: "Sandro Tonali", rating: 81 },
  { name: "Alessandro Bastoni", rating: 81 },
  { name: "Josko Gvardiol", rating: 81 },
  { name: "Matthijs de Ligt", rating: 81 },
  { name: "Dayot Upamecano", rating: 81 },
  { name: "Ibrahima Konaté", rating: 81 },
  { name: "Jules Koundé", rating: 81 },
  { name: "Reece James", rating: 81 },
  { name: "Ben White", rating: 81 },
  { name: "Kieran Trippier", rating: 81 },
  { name: "Kyle Walker", rating: 81 },
  { name: "John Stones", rating: 81 },
  { name: "Manuel Akanji", rating: 81 },
  { name: "Nathan Aké", rating: 81 },
  { name: "Oleksandr Zinchenko", rating: 80 },
  { name: "Lisandro Martínez", rating: 80 },
  { name: "Raphaël Varane", rating: 80 },
  { name: "Casemiro", rating: 80 },
  { name: "Christian Eriksen", rating: 80 },
  { name: "Mason Mount", rating: 80 },
  { name: "James Maddison", rating: 80 },
  { name: "Lucas Paquetá", rating: 80 },
  { name: "Dominik Szoboszlai", rating: 80 },
  { name: "Moisés Caicedo", rating: 80 },
  { name: "Pervis Estupiñán", rating: 80 },
  { name: "Kaoru Mitoma", rating: 80 },
  { name: "Evan Ferguson", rating: 78 },
  { name: "Alejandro Garnacho", rating: 79 },
  { name: "Rasmus Højlund", rating: 79 },
  { name: "Kobbie Mainoo", rating: 77 },
  { name: "Cole Palmer", rating: 83 },
  { name: "Conor Gallagher", rating: 80 },
  { name: "Anthony Gordon", rating: 80 },
  { name: "Jarrod Bowen", rating: 80 },
  { name: "Ollie Watkins", rating: 82 },
  { name: "Ivan Toney", rating: 81 },
  { name: "Dominic Solanke", rating: 80 },
  { name: "Pedro Neto", rating: 80 },
  { name: "João Palhinha", rating: 82 },
  { name: "Matheus Nunes", rating: 79 },
  { name: "Diogo Costa", rating: 82 },
  { name: "Gonçalo Ramos", rating: 80 },
  { name: "João Félix", rating: 81 },
  { name: "Raphinha", rating: 82 },
  { name: "Ferran Torres", rating: 80 },
  { name: "Lamine Yamal", rating: 82 },
  { name: "Nico Williams", rating: 81 },
  { name: "Dani Olmo", rating: 82 },
  { name: "Mikel Merino", rating: 81 },
  { name: "Fabián Ruiz", rating: 81 },
  { name: "Unai Simón", rating: 82 },
  { name: "David Raya", rating: 81 },
  { name: "Robert Sánchez", rating: 79 },
  { name: "Kepa Arrizabalaga", rating: 79 },
  { name: "Pau Torres", rating: 81 },
  { name: "Aymeric Laporte", rating: 81 },
  { name: "Robin Le Normand", rating: 80 },
  { name: "Dani Carvajal", rating: 82 },
  { name: "Jesus Navas", rating: 79 },
  { name: "Alejandro Grimaldo", rating: 83 },
  { name: "Jeremie Frimpong", rating: 83 },
  { name: "Xavi Simons", rating: 82 },
  { name: "Lois Openda", rating: 81 },
  { name: "Benjamin Sesko", rating: 79 },
  { name: "Gregor Kobel", rating: 83 },
  { name: "Yann Sommer", rating: 82 },
  { name: "Granit Xhaka", rating: 82 },
  { name: "Hakan Çalhanoğlu", rating: 83 },
  { name: "Arda Güler", rating: 78 },
  { name: "Kenan Yildiz", rating: 76 },
  { name: "Ferdi Kadıoğlu", rating: 79 },
  { name: "Kim Min-jae", rating: 83 },
  { name: "Lee Kang-in", rating: 80 },
  { name: "Takefusa Kubo", rating: 80 },
  { name: "Kaoru Mitoma", rating: 81 },
  { name: "Wataru Endo", rating: 79 },
  { name: "Takehiro Tomiyasu", rating: 79 },
  { name: "Mohammed Kudus", rating: 81 },
  { name: "Serhou Guirassy", rating: 81 },
  { name: "Victor Boniface", rating: 80 },
  { name: "Edmond Tapsoba", rating: 81 },
  { name: "Odilon Kossounou", rating: 80 },
  { name: "Piero Hincapié", rating: 80 },
  { name: "Exequiel Palacios", rating: 80 },
  { name: "Nico Schlotterbeck", rating: 81 },
  { name: "Niklas Süle", rating: 80 },
  { name: "Julian Brandt", rating: 81 },
  { name: "Donyell Malen", rating: 80 },
  { name: "Karim Adeyemi", rating: 79 },
  { name: "Jadon Sancho", rating: 81 },
  { name: "Ian Maatsen", rating: 78 },
  { name: "Mats Hummels", rating: 81 },
  { name: "Emre Can", rating: 79 },
  { name: "Marcel Sabitzer", rating: 80 },
  { name: "Konrad Laimer", rating: 80 },
  { name: "Leon Goretzka", rating: 81 },
  { name: "Sergej Milinković-Savić", rating: 82 },
  { name: "Aleksandar Mitrović", rating: 80 },
  { name: "Kalidou Koulibaly", rating: 81 },
  { name: "Edouard Mendy", rating: 80 },
  { name: "Roberto Firmino", rating: 80 },
  { name: "Franck Kessié", rating: 80 },
  { name: "Marcelo Brozović", rating: 80 },
  { name: "Aymeric Laporte", rating: 82 },
  { name: "Gabri Veiga", rating: 78 },
  { name: "Neymar Jr", rating: 88 },
  { name: "Malcom", rating: 81 },
  { name: "Ruben Neves", rating: 80 },
  { name: "Otávio", rating: 80 },
  { name: "Talisca", rating: 80 }
];

// Helper to get rating
function getPlayerRating(name) {
  const player = playerDatabase.find(p => p.name === name);
  if (player) return player.rating;
  
  // Default random rating for unknown players
  return Math.floor(Math.random() * (85 - 60 + 1)) + 60;
}

// Helper to get a random player from the database
function getRandomPlayerFromDB() {
  return playerDatabase[Math.floor(Math.random() * playerDatabase.length)];
}
