const playerDatabase = [
  { name: "Cristiano Ronaldo", rating: 99, position: "FWD" },
  { name: "Lionel Messi", rating: 99, position: "FWD" },
  { name: "Kylian Mbappé", rating: 95, position: "FWD" },
  { name: "Erling Haaland", rating: 95, position: "FWD" },
  { name: "Kevin De Bruyne", rating: 91, position: "MID" },
  { name: "Rodri", rating: 90, position: "MID" },
  { name: "Harry Kane", rating: 92, position: "FWD" },
  { name: "Vinícius Jr.", rating: 90, position: "FWD" },
  { name: "Mohamed Salah", rating: 91, position: "FWD" },
  { name: "Robert Lewandowski", rating: 91, position: "FWD" },
  { name: "Thibaut Courtois", rating: 91, position: "GK" },
  { name: "Alisson Becker", rating: 90, position: "GK" },
  { name: "Marc-André ter Stegen", rating: 90, position: "GK" },
  { name: "Virgil van Dijk", rating: 90, position: "DEF" },
  { name: "Rúben Dias", rating: 89, position: "DEF" },
  { name: "Bernardo Silva", rating: 89, position: "MID" },
  { name: "Jude Bellingham", rating: 89, position: "MID" },
  { name: "Luka Modrić", rating: 88, position: "MID" },
  { name: "Toni Kroos", rating: 88, position: "MID" },
  { name: "Bruno Fernandes", rating: 88, position: "MID" },
  { name: "Antoine Griezmann", rating: 88, position: "FWD" },
  { name: "Son Heung-min", rating: 87, position: "FWD" },
  { name: "Neymar Jr", rating: 87, position: "FWD" },
  { name: "Karim Benzema", rating: 87, position: "FWD" },
  { name: "Joshua Kimmich", rating: 87, position: "MID" },
  { name: "Jan Oblak", rating: 87, position: "GK" },
  { name: "Ederson", rating: 87, position: "GK" },
  { name: "Bukayo Saka", rating: 86, position: "FWD" },
  { name: "Martin Ødegaard", rating: 86, position: "MID" },
  { name: "Frenkie de Jong", rating: 86, position: "MID" },
  { name: "Pedri", rating: 86, position: "MID" },
  { name: "Rafael Leão", rating: 86, position: "FWD" },
  { name: "Victor Osimhen", rating: 86, position: "FWD" },
  { name: "Lautaro Martínez", rating: 86, position: "FWD" },
  { name: "Paulo Dybala", rating: 85, position: "FWD" },
  { name: "Ilkay Gündoğan", rating: 85, position: "MID" },
  { name: "Declan Rice", rating: 85, position: "MID" },
  { name: "William Saliba", rating: 85, position: "DEF" },
  { name: "Achraf Hakimi", rating: 85, position: "DEF" },
  { name: "Trent Alexander-Arnold", rating: 85, position: "DEF" },
  { name: "Alphonso Davies", rating: 84, position: "DEF" },
  { name: "Theo Hernández", rating: 84, position: "DEF" },
  { name: "João Cancelo", rating: 84, position: "DEF" },
  { name: "Marquinhos", rating: 84, position: "DEF" },
  { name: "Eder Militão", rating: 84, position: "DEF" },
  { name: "Ronald Araújo", rating: 84, position: "DEF" },
  { name: "Mike Maignan", rating: 84, position: "GK" },
  { name: "Emiliano Martínez", rating: 84, position: "GK" },
  { name: "Bruno Guimarães", rating: 84, position: "MID" },
  { name: "Jamal Musiala", rating: 84, position: "MID" },
  { name: "Phil Foden", rating: 84, position: "MID" },
  { name: "Florian Wirtz", rating: 84, position: "MID" },
  { name: "Khvicha Kvaratskhelia", rating: 84, position: "FWD" },
  { name: "Marcus Rashford", rating: 83, position: "FWD" },
  { name: "Jack Grealish", rating: 83, position: "MID" },
  { name: "Ousmane Dembélé", rating: 83, position: "FWD" },
  { name: "Kingsley Coman", rating: 83, position: "FWD" },
  { name: "Leroy Sané", rating: 83, position: "FWD" },
  { name: "Serge Gnabry", rating: 83, position: "FWD" },
  { name: "Federico Valverde", rating: 83, position: "MID" },
  { name: "Eduardo Camavinga", rating: 83, position: "MID" },
  { name: "Aurélien Tchouaméni", rating: 83, position: "MID" },
  { name: "Gavi", rating: 83, position: "MID" },
  { name: "Enzo Fernández", rating: 82, position: "MID" },
  { name: "Alexis Mac Allister", rating: 82, position: "MID" },
  { name: "Julian Álvarez", rating: 82, position: "FWD" },
  { name: "Darwin Núñez", rating: 82, position: "FWD" },
  { name: "Luis Díaz", rating: 82, position: "FWD" },
  { name: "Cody Gakpo", rating: 82, position: "FWD" },
  { name: "Diogo Jota", rating: 82, position: "FWD" },
  { name: "Alexander Isak", rating: 82, position: "FWD" },
  { name: "Gabriel Jesus", rating: 82, position: "FWD" },
  { name: "Gabriel Martinelli", rating: 82, position: "FWD" },
  { name: "Kai Havertz", rating: 82, position: "MID" },
  { name: "Raheem Sterling", rating: 81, position: "FWD" },
  { name: "Riyad Mahrez", rating: 81, position: "FWD" },
  { name: "Sadio Mané", rating: 81, position: "FWD" },
  { name: "N'Golo Kanté", rating: 81, position: "MID" },
  { name: "Paul Pogba", rating: 81, position: "MID" },
  { name: "Marco Reus", rating: 81, position: "MID" },
  { name: "Thomas Müller", rating: 81, position: "FWD" },
  { name: "Angel Di Maria", rating: 81, position: "FWD" },
  { name: "Olivier Giroud", rating: 81, position: "FWD" },
  { name: "Ciro Immobile", rating: 81, position: "FWD" },
  { name: "Romelu Lukaku", rating: 81, position: "FWD" },
  { name: "Dusan Vlahović", rating: 81, position: "FWD" },
  { name: "Federico Chiesa", rating: 81, position: "FWD" },
  { name: "Nicolo Barella", rating: 81, position: "MID" },
  { name: "Sandro Tonali", rating: 81, position: "MID" },
  { name: "Alessandro Bastoni", rating: 81, position: "DEF" },
  { name: "Josko Gvardiol", rating: 81, position: "DEF" },
  { name: "Matthijs de Ligt", rating: 81, position: "DEF" },
  { name: "Dayot Upamecano", rating: 81, position: "DEF" },
  { name: "Ibrahima Konaté", rating: 81, position: "DEF" },
  { name: "Jules Koundé", rating: 81, position: "DEF" },
  { name: "Reece James", rating: 81, position: "DEF" },
  { name: "Ben White", rating: 81, position: "DEF" },
  { name: "Kieran Trippier", rating: 81, position: "DEF" },
  { name: "Kyle Walker", rating: 81, position: "DEF" },
  { name: "John Stones", rating: 81, position: "DEF" },
  { name: "Manuel Akanji", rating: 81, position: "DEF" },
  { name: "Nathan Aké", rating: 81, position: "DEF" },
  { name: "Oleksandr Zinchenko", rating: 80, position: "DEF" },
  { name: "Lisandro Martínez", rating: 80, position: "DEF" },
  { name: "Raphaël Varane", rating: 80, position: "DEF" },
  { name: "Casemiro", rating: 80, position: "MID" },
  { name: "Christian Eriksen", rating: 80, position: "MID" },
  { name: "Mason Mount", rating: 80, position: "MID" },
  { name: "James Maddison", rating: 80, position: "MID" },
  { name: "Lucas Paquetá", rating: 80, position: "MID" },
  { name: "Dominik Szoboszlai", rating: 80, position: "MID" },
  { name: "Moisés Caicedo", rating: 80, position: "MID" },
  { name: "Pervis Estupiñán", rating: 80, position: "DEF" },
  { name: "Kaoru Mitoma", rating: 80, position: "FWD" },
  { name: "Evan Ferguson", rating: 78, position: "FWD" },
  { name: "Alejandro Garnacho", rating: 79, position: "FWD" },
  { name: "Rasmus Højlund", rating: 79, position: "FWD" },
  { name: "Kobbie Mainoo", rating: 77, position: "MID" },
  { name: "Cole Palmer", rating: 83, position: "MID" },
  { name: "Conor Gallagher", rating: 80, position: "MID" },
  { name: "Anthony Gordon", rating: 80, position: "FWD" },
  { name: "Jarrod Bowen", rating: 80, position: "FWD" },
  { name: "Ollie Watkins", rating: 82, position: "FWD" },
  { name: "Ivan Toney", rating: 81, position: "FWD" },
  { name: "Dominic Solanke", rating: 80, position: "FWD" },
  { name: "Pedro Neto", rating: 80, position: "FWD" },
  { name: "João Palhinha", rating: 82, position: "MID" },
  { name: "Matheus Nunes", rating: 79, position: "MID" },
  { name: "Diogo Costa", rating: 82, position: "GK" },
  { name: "Gonçalo Ramos", rating: 80, position: "FWD" },
  { name: "João Félix", rating: 81, position: "FWD" },
  { name: "Raphinha", rating: 82, position: "FWD" },
  { name: "Ferran Torres", rating: 80, position: "FWD" },
  { name: "Lamine Yamal", rating: 82, position: "FWD" },
  { name: "Nico Williams", rating: 81, position: "FWD" },
  { name: "Dani Olmo", rating: 82, position: "MID" },
  { name: "Mikel Merino", rating: 81, position: "MID" },
  { name: "Fabián Ruiz", rating: 81, position: "MID" },
  { name: "Unai Simón", rating: 82, position: "GK" },
  { name: "David Raya", rating: 81, position: "GK" },
  { name: "Robert Sánchez", rating: 79, position: "GK" },
  { name: "Kepa Arrizabalaga", rating: 79, position: "GK" },
  { name: "Pau Torres", rating: 81, position: "DEF" },
  { name: "Aymeric Laporte", rating: 81, position: "DEF" },
  { name: "Robin Le Normand", rating: 80, position: "DEF" },
  { name: "Dani Carvajal", rating: 82, position: "DEF" },
  { name: "Jesus Navas", rating: 79, position: "DEF" },
  { name: "Alejandro Grimaldo", rating: 83, position: "DEF" },
  { name: "Jeremie Frimpong", rating: 83, position: "DEF" },
  { name: "Xavi Simons", rating: 82, position: "MID" },
  { name: "Lois Openda", rating: 81, position: "FWD" },
  { name: "Benjamin Sesko", rating: 79, position: "FWD" },
  { name: "Gregor Kobel", rating: 83, position: "GK" },
  { name: "Yann Sommer", rating: 82, position: "GK" },
  { name: "Granit Xhaka", rating: 82, position: "MID" },
  { name: "Hakan Çalhanoğlu", rating: 83, position: "MID" },
  { name: "Arda Güler", rating: 78, position: "MID" },
  { name: "Kenan Yildiz", rating: 76, position: "FWD" },
  { name: "Ferdi Kadıoğlu", rating: 79, position: "DEF" },
  { name: "Kim Min-jae", rating: 83, position: "DEF" },
  { name: "Lee Kang-in", rating: 80, position: "MID" },
  { name: "Takefusa Kubo", rating: 80, position: "FWD" },
  { name: "Wataru Endo", rating: 79, position: "MID" },
  { name: "Takehiro Tomiyasu", rating: 79, position: "DEF" },
  { name: "Mohammed Kudus", rating: 81, position: "FWD" },
  { name: "Serhou Guirassy", rating: 81, position: "FWD" },
  { name: "Victor Boniface", rating: 80, position: "FWD" },
  { name: "Edmond Tapsoba", rating: 81, position: "DEF" },
  { name: "Odilon Kossounou", rating: 80, position: "DEF" },
  { name: "Piero Hincapié", rating: 80, position: "DEF" },
  { name: "Exequiel Palacios", rating: 80, position: "MID" },
  { name: "Nico Schlotterbeck", rating: 81, position: "DEF" },
  { name: "Niklas Süle", rating: 80, position: "DEF" },
  { name: "Julian Brandt", rating: 81, position: "MID" },
  { name: "Donyell Malen", rating: 80, position: "FWD" },
  { name: "Karim Adeyemi", rating: 79, position: "FWD" },
  { name: "Jadon Sancho", rating: 81, position: "FWD" },
  { name: "Ian Maatsen", rating: 78, position: "DEF" },
  { name: "Mats Hummels", rating: 81, position: "DEF" },
  { name: "Emre Can", rating: 79, position: "MID" },
  { name: "Marcel Sabitzer", rating: 80, position: "MID" },
  { name: "Konrad Laimer", rating: 80, position: "MID" },
  { name: "Leon Goretzka", rating: 81, position: "MID" },
  { name: "Sergej Milinković-Savić", rating: 82, position: "MID" },
  { name: "Aleksandar Mitrović", rating: 80, position: "FWD" },
  { name: "Kalidou Koulibaly", rating: 81, position: "DEF" },
  { name: "Edouard Mendy", rating: 80, position: "GK" },
  { name: "Roberto Firmino", rating: 80, position: "FWD" },
  { name: "Franck Kessié", rating: 80, position: "MID" },
  { name: "Marcelo Brozović", rating: 80, position: "MID" },
  { name: "Gabri Veiga", rating: 78, position: "MID" },
  { name: "Malcom", rating: 81, position: "FWD" },
  { name: "Ruben Neves", rating: 80, position: "MID" },
  { name: "Otávio", rating: 80, position: "MID" },
  { name: "Talisca", rating: 80, position: "FWD" },
  { name: "Zlatan Ibrahimović", rating: 85, position: "FWD" },
  { name: "Sergio Ramos", rating: 84, position: "DEF" },
  { name: "Luis Suárez", rating: 84, position: "FWD" },
  { name: "Eden Hazard", rating: 82, position: "FWD" },
  { name: "Thiago Silva", rating: 85, position: "DEF" },
  { name: "Giorgio Chiellini", rating: 83, position: "DEF" },
  { name: "Leonardo Bonucci", rating: 82, position: "DEF" },
  { name: "Manuel Neuer", rating: 89, position: "GK" },
  { name: "Gianluigi Buffon", rating: 85, position: "GK" },
  { name: "Andrés Iniesta", rating: 86, position: "MID" },
  { name: "Wesley Sneijder", rating: 84, position: "MID" },
  { name: "Mesut Özil", rating: 83, position: "MID" },
  { name: "Gareth Bale", rating: 85, position: "FWD" },
  { name: "Sergio Agüero", rating: 87, position: "FWD" },
  { name: "Gonzalo Higuaín", rating: 84, position: "FWD" },
  { name: "Diego Costa", rating: 83, position: "FWD" },
  { name: "Franck Ribéry", rating: 85, position: "FWD" },
  { name: "Arjen Robben", rating: 86, position: "FWD" },
  { name: "Radamel Falcao", rating: 84, position: "FWD" },
  { name: "Diego Forlán", rating: 83, position: "FWD" },
  // Legends
  { name: "Pelé", rating: 98, position: "FWD", type: "Icon" },
  { name: "Diego Maradona", rating: 96, position: "MID", type: "Icon" },
  { name: "Ronaldo Nazário", rating: 97, position: "FWD", type: "Icon" },
  { name: "Zinedine Zidane", rating: 97, position: "MID", type: "Icon" },
  { name: "Johan Cruyff", rating: 96, position: "FWD", type: "Icon" },
  { name: "Franz Beckenbauer", rating: 96, position: "DEF", type: "Icon" },
  { name: "Paolo Maldini", rating: 96, position: "DEF", type: "Icon" },
  { name: "Lev Yashin", rating: 96, position: "GK", type: "Icon" },
  { name: "Ronaldinho", rating: 96, position: "FWD", type: "Icon" },
  { name: "Thierry Henry", rating: 95, position: "FWD", type: "Icon" },
  { name: "Xavi Hernández", rating: 94, position: "MID", type: "Icon" },
  { name: "Roberto Carlos", rating: 93, position: "DEF", type: "Icon" },
  { name: "Cafu", rating: 93, position: "DEF", type: "Icon" },
  { name: "Iker Casillas", rating: 93, position: "GK", type: "Icon" },
  { name: "Oliver Kahn", rating: 93, position: "GK", type: "Icon" },
  { name: "Carles Puyol", rating: 92, position: "DEF", type: "Icon" },
  { name: "Fabio Cannavaro", rating: 93, position: "DEF", type: "Icon" },
  { name: "Andrea Pirlo", rating: 93, position: "MID", type: "Icon" },
  { name: "Steven Gerrard", rating: 91, position: "MID", type: "Icon" },
  { name: "Frank Lampard", rating: 91, position: "MID", type: "Icon" },
  { name: "Paul Scholes", rating: 91, position: "MID", type: "Icon" },
  { name: "David Beckham", rating: 90, position: "MID", type: "Icon" },
  { name: "Wayne Rooney", rating: 90, position: "FWD", type: "Icon" },
  { name: "Kaka", rating: 93, position: "MID", type: "Icon" },
  { name: "Samuel Eto'o", rating: 91, position: "FWD", type: "Icon" },
  { name: "Didier Drogba", rating: 90, position: "FWD", type: "Icon" },
  { name: "Ruud Gullit", rating: 94, position: "MID", type: "Icon" },
  { name: "Marco van Basten", rating: 94, position: "FWD", type: "Icon" },
  { name: "Franco Baresi", rating: 94, position: "DEF", type: "Icon" },
  { name: "Alessandro Nesta", rating: 92, position: "DEF", type: "Icon" },
  { name: "Peter Schmeichel", rating: 92, position: "GK", type: "Icon" },
  { name: "Edwin van der Sar", rating: 90, position: "GK", type: "Icon" }
];

